import type { ContentSnapshot } from "./types";

export const SEED: ContentSnapshot = {
  profile: {
    name: "Omar Tarek Eldeeb",
    title: "AI Engineer / Machine Learning Engineer",
    faculty: "Faculty of Engineering — Artificial Intelligence",
    location: "Cairo, Egypt",
    email: "eldeebomar440@gmail.com",
    about:
      "AI Engineer and Machine Learning Engineer based in Cairo, Egypt. Faculty of Engineering — Artificial Intelligence.",
    avatarUrl: null,
  },
  socials: [
    {
      id: "social_email",
      label: "Email",
      url: "mailto:eldeebomar440@gmail.com",
      published: true,
      sortOrder: 0,
    },
    {
      id: "social_linkedin",
      label: "LinkedIn",
      url: "https://linkedin.com/in/omar-tarek-6b9611332",
      published: true,
      sortOrder: 1,
    },
    {
      id: "social_github",
      label: "GitHub",
      url: "https://github.com/eldeebomar440-stack",
      published: true,
      sortOrder: 2,
    },
  ],
  projects: [
    {
      id: "proj_maze",
      title: "Maze Bot",
      summary: "AI-based maze-solving robot",
      description: "AI-based maze-solving robot",
      imageUrl: "/media/maze-bot.jpg",
      liveUrl: null,
      repoUrl: null,
      tags: ["AI"],
      featured: true,
      published: true,
      sortOrder: 0,
    },
    {
      id: "proj_house",
      title: "House Price Prediction",
      summary: "Machine Learning project",
      description: "Machine Learning project",
      imageUrl: "/media/house-price.jpg",
      liveUrl: null,
      repoUrl: null,
      tags: ["Machine Learning"],
      featured: true,
      published: true,
      sortOrder: 1,
    },
  ],
  certificates: [],
  experience: [
    {
      id: "exp_nti",
      title: "Training",
      organization: "NTI",
      summary: "",
      startedOn: null,
      endedOn: null,
      published: true,
      sortOrder: 0,
    },
    {
      id: "exp_depi",
      title: "Training",
      organization: "DEPI",
      summary: "",
      startedOn: null,
      endedOn: null,
      published: true,
      sortOrder: 1,
    },
    {
      id: "exp_lia",
      title: "AI & Machine Learning",
      organization: "LIA",
      summary: "",
      startedOn: null,
      endedOn: null,
      published: true,
      sortOrder: 2,
    },
  ],
  skills: [],
  education: [
    {
      id: "edu_faculty",
      institution: "Faculty of Engineering",
      program: "Artificial Intelligence",
      summary: "",
      startedOn: null,
      endedOn: null,
      published: true,
      sortOrder: 0,
    },
  ],
};
